#!/usr/bin/env ruby
# frozen_string_literal: true
require 'sinatra'
require 'yaml'
require 'tilt/erb'
require 'kollus'

path_secret = File.join File.dirname(__FILE__), 'secret.yml'
config = YAML.load_file(path_secret)

set :bind, config['bind']
set :port, config['port']

kollus = Kollus.new config['account_key'], config['api_token']

get '/' do
  @media1 = kollus.media config['media1_key'], 'test'
  @media2 = kollus.media config['media2_key'], 'test'
  @upload = kollus.upload config['category_key']

  erb :index
end
